#!/bin/bash

echo "[dind] starting service" >&2
# sleep 1s helps workaround the "sed: couldn't flush stdout: Device or resource busy"
# error on first startup attempt
exec s6-notifyoncheck -c /etc/s6-overlay/s6-rc.d/dind/check_readiness.sh \
    bash -c 'sleep 1s && exec dind dockerd'
