// Generate an "unique" port for SSHD
env.SSHD_PORT = new Random(env.BUILD_TAG.hashCode()).nextInt(23000 - 22000) + 22000
pipeline {
    agent any
    options {
        timeout(time: 10, unit: 'MINUTES')
        ansiColor('xterm')
    }
    stages {
        stage ('prepare') {
            steps {
                // docker can only pull from insecure registries at localhost by default
                sh 'docker run --name socat -d --network=host alpine/socat tcp-listen:15432,reuseaddr,fork tcp:jenkins-agent-dind-test-registry:5000'
                retry(3) {
                    sh 'docker pull localhost:15432/jenkins-agent-dind:latest'
                }
            }
            post {
                failure {
                    sh 'docker logs socat'
                }
            }
        }
        stage('parallel') {
            parallel {
                stage ('docker') {
                    steps {
                        sh 'printenv | sort | tee /dev/stderr | grep -q ^USER='
                        sh 'docker version'
                        sh 'IGNORE_FAILURE=false /ssh-command/get.sh'
                    }
                }
                stage ('nested dond') {
                    agent {
                        docker {
                            reuseNode true
                            image 'localhost:15432/jenkins-agent-dind:latest'
                            args '--volume=/ssh-command:/ssh-command --volume=/var/run/docker.sock:/var/run/docker.sock --group-add=docker --network=host'
                        }
                    }
                    steps {
                        sh 'printenv | sort | tee /dev/stderr | grep -q ^USER='
                        sh 'docker version'
                        sh 'IGNORE_FAILURE=false /ssh-command/get.sh'
                    }
                }
                stage ('nested dind') {
                    agent {
                        docker {
                            reuseNode true
                            image 'localhost:15432/jenkins-agent-dind:latest'
                            args "--privileged --group-add=docker --env=SSHD_ENABLED=true --publish=^${env.SSHD_PORT}:22 --env=DOMAIN=example.com"
                        }
                    }
                    steps {
                        sh 'docker version'
                        sh 'printenv | sort | tee /dev/stderr | grep -q ^USER='
                        sh 'IGNORE_FAILURE=false /ssh-command/get.sh'
                    }
                }
                stage ('docker compose') {
                    steps {
                        sh 'docker compose version'
                        sh 'docker-compose version'
                        writeFile file: 'docker-compose.yaml', text: '''\
                            services:
                                service1:
                                    image: test1
                                    pull_policy: build
                                    build:
                                        dockerfile_inline: FROM busybox
                                    command:
                                        - echo
                                        - service 1 success
                                service2:
                                    depends_on:
                                        service1:
                                          condition: service_completed_successfully
                                    image: busybox
                                    pull_policy: always
                                    command:
                                        - sh
                                        - -c
                                        - exit 123
                            '''.stripIndent()
                        sh 'cat docker-compose.yaml'
                        sh 'set +e; docker compose up --exit-code-from service2; test $? -eq 123'
                    }
                }
                stage ('volta') {
                    steps {
                        retry(3) {
                            sh 'volta install node@18.20.4 npm@9.9.3'
                        }
                        sh 'node --version | grep ^v18.20.4$'
                        sh 'npm --version | grep ^9.9.3$'
                    }
                }
            }
        }
    }
    // post {
    //     failure {
    //         sh 'sleep 5m'
    //     }
    // }
}
